### ISSUE TITLE
Add autoscaling values support for min-max count =0

### ISSUE THREAD

**Issue by jmolla31** [cloudcommons/terraform-azure-kubernetes#3]
Both **auto_scaling_min_count** and **auto_scaling_max_count** only allow a valid input range from 1-100

They should allow 0 when **auto_scaling_enable** is set to false, since Terraform requires that *max_count* and *min_count* must be set to 0 if autoscaling is set to *false*

**Comment by sesispla** [comment]
@jmolla31 I can't see any validation that don't allow you to put "0" to auto_scaling_min_count and auto_scaling_max_count, but default values that you should override if you turn off autoscaling:

https://github.com/cloudcommons/terraform-azure-kubernetes/blob/36b84fa164bcdd973ae08c20196728eaf832417a/variables.tf#L96-L112

Could you please provide me with steps to reproduce the issue?

**Comment by sesispla** [comment]
Got you! :)
